parameters:
  - name: containerRegistryServiceConnection
    default: 'dockerhub'
  - name: imageRepository
    default: 'azure-vote-app'
  - name: containerRegistry
    default: 'docker.io'
  - name: dockerfilePath
    default: 'azure-vote/Dockerfile'
  - name: tag
    default: 'v2'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Image Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'dockerhub'

    - script: |
        # Build the Docker image and tag it
        docker build -f ${{ parameters.dockerfilePath }} -t ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:${{ parameters.tag }} .
        
        # List images to confirm it is tagged correctly
        docker images
        
        # Push the Docker image to Docker Hub
        docker push ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:${{ parameters.tag }}
      displayName: 'Build and Push Docker Image'
