jobs:
  - job: Build
    displayName: Build and Push Docker Image
    steps:
      - task: Docker@2
        displayName: Docker Build
        inputs:
          command: build
          dockerFile: $(Build.SourcesDirectory)/azure-vote/Dockerfile
          tags: $(tag)
          buildContext: $(Build.SourcesDirectory)

      - task: Docker@2
        displayName: Docker Push
        inputs:
          command: push
          repository: gudshuis/$(imageRepository)
          tags: $(tag)
          containerRegistry: $(dockerServiceConnection)  # Docker Hub service connection
