variables:
  containerRegistry: 'dockerhub'
  imageRepository: 'azure-vote-app'
  tag: 'v2'
  kubernetesServiceConnection: 'az-k8s'  # Kubernetes service connection
  dockerServiceConnection: 'dockerhub'   # Docker Hub service connection
  timestamp: $[format('{0:yyyyMMdd-HHmmss}', pipeline().startTime)]  # Current timestamp

jobs:
  - job: Build
    displayName: Build and Push Docker Image
    steps:
      # Step 1: Build the Docker image
      - task: Docker@2
        displayName: Docker Build
        inputs:
          command: build
          dockerFile: $(Build.SourcesDirectory)/azure-vote/Dockerfile
          tags: $(tag)  # Don't rely on full tag here
          buildContext: $(Build.SourcesDirectory)

      # Step 2: Debugging step to list all Docker images
      - script: |
          echo "Listing all Docker images:"
          docker images
        displayName: 'List Docker Images for Debugging'

      # Step 3: Rename any untagged image with today's date and time
      - script: |
          echo "Checking for untagged images..."
          # Find the image ID of the untagged image
          IMAGE_ID=$(docker images -q --filter "dangling=true")
          if [ -n "$IMAGE_ID" ]; then
            echo "Found untagged image, renaming it with today's timestamp."
            # Rename the image with a new tag based on today's timestamp
            docker tag $IMAGE_ID gudshuis/$(imageRepository):$(timestamp)
            echo "Renamed image to gudshuis/$(imageRepository):$(timestamp)"
          else
            echo "No untagged image found."
          fi
        displayName: 'Rename Untagged Image with Timestamp'

      # Step 4: Push the Docker image to Docker Hub
      - task: Docker@2
        displayName: Docker Push
        inputs:
          command: push
          repository: gudshuis/$(imageRepository)
          tags: $(timestamp)  # Use the timestamp as the tag
          containerRegistry: $(dockerServiceConnection)  # Docker Hub service connection
