pool:
  name: 'Default'  # This refers to the default agent pool
  demands:
    - agent.name -equals BuildAgent  # This ensures the "BuildAgent" is specifically used

jobs:
- job: BuildAndPush
  displayName: Build and Push Docker Image
  steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'dockerhub'

    - script: |
        # Build the Docker image
        docker build -t ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:${{ parameters.tag }} ${{ parameters.dockerfilePath }}
        
        # List Docker images to confirm the build and tag
        docker images
        
        # If the image is built but not tagged, tag it explicitly
        docker tag ${{ parameters.imageRepository }}:${{ parameters.tag }} ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:${{ parameters.tag }}
        
        # Now push the image
        docker push ${{ parameters.containerRegistry }}/${{ parameters.imageRepository }}:${{ parameters.tag }}
      displayName: 'Build and Push Docker Image'
