parameters:
  aksCluster: $(aksCluster)
  aksNamespace: $(aksNamespace)
  imagePullSecret: $(imagePullSecret)

stages:
- stage: Deploy
  displayName: Deploy to Kubernetes
  dependsOn: Build
  jobs:
  - deployment: DeployApp
    displayName: Deploy to AKS
    environment: $(aksCluster)
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Manifest File
            inputs:
              artifactName: drop
              targetPath: $(Pipeline.Workspace)

          - task: KubernetesManifest@0
            displayName: Apply Kubernetes Manifest
            inputs:
              action: deploy
              manifests: $(Pipeline.Workspace)/$(manifestFileName)
              containers: |
                azure-vote=$(acrName)/azure-vote:$(tag)
              imagePullSecrets: $(imagePullSecret)
              namespace: $(aksNamespace)

          - task: AzureMonitor@1
            displayName: Enable Azure Monitor Insights
            inputs:
              monitorNamespace: $(aksNamespace)
              monitorCluster: $(aksCluster)
