parameters:
  acrName: $(acrName)
  resourceGroup: $(resourceGroup)
  dockerfilePath: $(dockerfilePath)
  tag: $(tag)

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: BuildAndPushImage
    displayName: Build and Push Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: $(acrName) # Azure Container Registry
        repository: azure-vote
        command: build
        Dockerfile: $(dockerfilePath) # Dynamically use Dockerfile path from variable
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push Docker Image to ACR
      inputs:
        containerRegistry: $(acrName)
        repository: azure-vote
        command: push
        tags: |
          $(tag)

    - script: echo "##vso[task.setvariable variable=imageName]azure-vote:$(tag)"
      displayName: Set Image Name Variable

  - job: ValidateBuild
    displayName: Run Validation Tests
    dependsOn: BuildAndPushImage
    steps:
    - script: echo "Validating the Docker image..."
      displayName: Validation Task
      continueOnError: true # Allow the job to continue even if validation fails
      condition: succeededOrFailed() # Ensure this task runs even if the build partially fails
