trigger:
  branches:
    include:
      - main
      - feature/*

# Import variable template
variables:
  - template: variables/var.yml   # Correct path to var.yml

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - template: stages/ci.yml

  - stage: Deploy
    displayName: Deploy Stage
    jobs:
      - template: stages/cd.yml
