# cd.yml
parameters:
  containerRegistry: ''
  imageRepository: ''
  tag: ''
  helmChartPath: ''
  helmReleaseName: ''
  helmNamespace: ''

stages:
  - stage: Deploy
    displayName: Deploy to AKS using Helm
    jobs:
      - job: Deploy
        displayName: Deploy with Helm
        steps:
          - task: HelmInstaller@0
            displayName: Install Helm
            inputs:
              helmVersionToInstall: 'latest'

          - task: HelmDeploy@0
            displayName: Deploy Application with Helm
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'your-azure-subscription'  # Set your Azure Subscription
              azureResourceGroup: 'your-resource-group'    # Specify your Azure Resource Group here
              kubernetesCluster: $(kubernetesCluster)
              namespace: $(helmNamespace)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: $(helmChartPath)
              releaseName: $(helmReleaseName)
              overrideValues: |
                image.repository=$(containerRegistry)/$(imageRepository)
                image.tag=$(tag)
                image.pullSecrets=crvoteapptestuks-auth
